.PHONY all:
all:
	gcc -Wall -D PART1 sfs.c -o diskinfo
	gcc -Wall -D PART2 sfs.c -o disklist
	gcc -Wall -D PART3 sfs.c -o diskget
	gcc -Wall -D PART4 sfs.c -o diskput
	gcc -Wall -D PART5 sfs.c -o diskfix

.PHONY clean:
clean:
	-rm diskinfo disklist diskget diskput diskfix